import json
import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_LOG_PATH = PROJECT_ROOT / "logs" / "query_log.jsonl"


def get_log_path() -> Path:
    """Return configured log file path from environment or default."""
    env_path = os.getenv("QUERY_LOG_PATH")
    if env_path:
        return Path(env_path)
    return DEFAULT_LOG_PATH


def log_query(
    question: str,
    retrieved_chunks: List[Dict[str, Any]],
    confidence_met: bool,
    top_score: float,
    final_answer: str,
    refused: bool,
    log_path: Optional[Path] = None,
    extra_metadata: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Log an end-to-end RAG query record in JSON Lines format.

    Fields:
      - timestamp: ISO 8601 UTC timestamp
      - question: user's query text
      - retrieved_chunks: list of retrieved chunk metadata & scores
      - confidence_met: whether top chunk score passed threshold
      - top_score: similarity score of the top chunk
      - final_answer: answer generated by LLM or refusal message
      - refused: boolean indicating if safety refusal was triggered
    """

    target_path = log_path or get_log_path()
    target_path.parent.mkdir(parents=True, exist_ok=True)

    log_entry: Dict[str, Any] = {
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "question": question,
        "retrieved_chunks": retrieved_chunks,
        "confidence_met": confidence_met,
        "top_score": round(float(top_score), 4) if top_score is not None else 0.0,
        "final_answer": final_answer,
        "refused": bool(refused),
    }

    if extra_metadata:
        log_entry["extra_metadata"] = extra_metadata

    try:
        with open(target_path, "a", encoding="utf-8") as f:
            f.write(json.dumps(log_entry, ensure_ascii=False) + "\n")
    except Exception as e:
        print(f"[QueryLogger Warning] Failed to write log: {e}")

    return log_entry


def get_logged_queries(log_path: Optional[Path] = None) -> List[Dict[str, Any]]:
    """
    Read all logged queries from the JSON Lines file.
    """
    target_path = log_path or get_log_path()

    if not target_path.exists():
        return []

    entries = []
    with open(target_path, "r", encoding="utf-8") as f:
        for line in f:
            line_str = line.strip()
            if line_str:
                try:
                    entries.append(json.loads(line_str))
                except json.JSONDecodeError:
                    continue

    return entries
